'use client';

import { useState } from 'react';
import { AppState, JTBDJob } from '@/lib/types';
import { BarChart3, Users, Target, ArrowRight, Presentation, Download } from 'lucide-react';
import { getVisiblePersonas, getVisibleJobs, getVisibleAgentOpportunities, isShowingSampleData } from '@/lib/data-utils';

interface PresentingModeProps {
  appState: AppState;
  updateAppState: (updates: Partial<AppState>) => void;
}

export default function PresentingMode({ appState }: PresentingModeProps) {
  // Get filtered data (hide sample data when real data exists)
  const visiblePersonas = getVisiblePersonas(appState.personas);
  const visibleJobs = getVisibleJobs(appState.jobs);
  const visibleAgentOpportunities = getVisibleAgentOpportunities(appState.agentOpportunities);
  const showingSampleData = isShowingSampleData(appState.personas, appState.jobs, appState.agentOpportunities);

  // Calculate metrics for executive brief
  const weeklyHours = Math.round(visibleJobs.reduce((acc, job) => {
    if (!job.timePerOccurrence || !job.frequency) return acc;
    const multiplier = { 'daily': 5, 'weekly': 1, 'monthly': 0.25, 'as-needed': 1 }[job.frequency] || 1;
    return acc + (job.timePerOccurrence * multiplier);
  }, 0) / 60);

  const automationSavings = Math.round(weeklyHours * 0.7);
  const highPriorityAgents = visibleAgentOpportunities.filter(a => a.priority === 'high').length;

  // Download Executive Brief as formatted text
  const downloadExecutiveBrief = () => {
    const briefContent = `
EXECUTIVE BRIEF: AGENTFORCE IMPLEMENTATION STRATEGY
${new Date().toLocaleDateString()}

EXECUTIVE SUMMARY
================
We recommend implementing ${highPriorityAgents} high-priority Agentforce agents to address ${automationSavings} hours per week of manual work across ${visiblePersonas.length} key personas. This automation initiative will deliver measurable ROI within 90 days through improved efficiency and customer experience.

PROBLEM STATEMENT
=================
Our analysis reveals ${visibleJobs.length} critical jobs-to-be-done consuming ${weeklyHours} hours per week of manual effort. Key pain points include repetitive customer inquiries, time-intensive research tasks, and manual data processing. Without automation, these inefficiencies will scale linearly with business growth, creating operational bottlenecks and reducing team capacity for strategic initiatives.

OPTIONS & TRADE-OFFS
===================
• Agentforce Implementation: High automation potential, seamless Salesforce integration.
  Risk: Learning curve for complex workflows.

• Status Quo + Hiring: Immediate capacity increase, proven approach.
  Risk: Higher costs, scaling limitations, knowledge retention.

• Third-party Tools: Specialized features, faster initial deployment.
  Risk: Integration complexity, data silos, ongoing costs.

RECOMMENDED EXECUTION PLAN
==========================
Phase 1: Foundation (Weeks 1-4)
- Deploy ${Math.min(2, highPriorityAgents)} high-priority agents
- Owner: IT Team

Phase 2: Scale (Weeks 5-8)
- Expand to remaining high-priority opportunities
- Owner: Operations Team

Phase 3: Optimize (Weeks 9-12)
- Monitor performance and refine based on usage data
- Owner: Business Team

SUCCESS METRICS & TARGETS
=========================
Efficiency Metrics:
• 70% reduction in manual processing time (Target: 90 days)
• 50% improvement in response times (Target: 60 days)
• 90% automation coverage for routine tasks (Target: 120 days)

Business Impact:
• 25% increase in team capacity for strategic work
• 15% improvement in customer satisfaction scores
• ROI positive within 90 days of full deployment

RISKS & MITIGATION STRATEGIES
============================
User Adoption: Team resistance to new workflows
→ Mitigation: Training program + change champions

Technical Complexity: Integration challenges with existing systems
→ Mitigation: Phased rollout + dedicated technical support

APPENDIX: CALCULATIONS & DATA SOURCES
====================================
Time Calculations:
- Weekly manual hours: ${weeklyHours} hours
- Automation potential: 70% (industry benchmark)
- Expected savings: ${automationSavings} hours/week

Data Sources:
- Jobs analysis: ${visibleJobs.length} documented jobs
- Persona research: ${visiblePersonas.length} key roles
- Agent opportunities: ${visibleAgentOpportunities.length} identified

Generated by JTBD Framework Builder
${window.location.hostname}
`;

    const blob = new Blob([briefContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Executive-Brief-Agentforce-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  };

  const jobsByType = visibleJobs.reduce((acc, job) => {
    acc[job.jobType] = (acc[job.jobType] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  // Calculate normalized weekly time by persona
  const timeByPersona = visibleJobs.reduce((acc, job) => {
    if (!job.timePerOccurrence || !job.frequency) return acc;

    const persona = visiblePersonas.find(p => p.id === job.persona);
    if (!persona) return acc;

    // Normalize to weekly time
    const multiplier = {
      'daily': 5,      // 5 work days per week
      'weekly': 1,     // Already weekly
      'monthly': 0.25, // ~1 week per month
      'as-needed': 1   // Assume weekly
    }[job.frequency] || 1;

    const weeklyMinutes = job.timePerOccurrence * multiplier;

    if (!acc[persona.id]) {
      acc[persona.id] = {
        personaName: persona.name,
        personaRole: persona.role,
        totalWeeklyMinutes: 0,
        jobCount: 0
      };
    }

    acc[persona.id].totalWeeklyMinutes += weeklyMinutes;
    acc[persona.id].jobCount += 1;

    return acc;
  }, {} as Record<string, { personaName: string; personaRole: string; totalWeeklyMinutes: number; jobCount: number }>);

  // Sort personas by total weekly time (descending)
  const sortedPersonaTime = Object.values(timeByPersona)
    .sort((a, b) => b.totalWeeklyMinutes - a.totalWeeklyMinutes);

  // Calculate total weekly time across all personas
  const totalWeeklyTime = sortedPersonaTime.reduce((sum, persona) => sum + persona.totalWeeklyMinutes, 0);

  const renderExecutiveDashboard = () => (
    <div className="space-y-8">
      {/* Key Metrics */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <div className="bg-white rounded-lg border p-6 text-center">
          <div className="text-3xl font-bold text-blue-600 mb-2">{visibleJobs.length}</div>
          <div className="text-sm text-gray-600">Jobs Identified</div>
        </div>

        <div className="bg-white rounded-lg border p-6 text-center">
          <div className="text-3xl font-bold text-green-600 mb-2">{visibleAgentOpportunities.length}</div>
          <div className="text-sm text-gray-600">Agent Opportunities</div>
        </div>

        <div className="bg-white rounded-lg border p-6 text-center">
          <div className="text-3xl font-bold text-purple-600 mb-2">{visiblePersonas.length}</div>
          <div className="text-sm text-gray-600">Personas Analyzed</div>
        </div>

        <div className="bg-white rounded-lg border p-6 text-center">
          <div className="text-3xl font-bold text-orange-600 mb-2">
            {Math.round((visibleAgentOpportunities.length / Math.max(visibleJobs.length, 1)) * 100)}%
          </div>
          <div className="text-sm text-gray-600">Automation Potential</div>
        </div>
      </div>

      {/* Time Impact Analysis */}
      <div className="bg-white rounded-lg border p-8">
        <h3 className="text-2xl font-bold text-gray-900 mb-6">Weekly Time Impact by Persona</h3>

        {sortedPersonaTime.length > 0 ? (
          <div className="space-y-4">
            <div className="text-sm text-gray-600 mb-4">
              Total weekly time across all personas: <span className="font-semibold text-gray-900">
                {Math.round(totalWeeklyTime)} minutes ({(totalWeeklyTime / 60).toFixed(1)} hours)
              </span>
            </div>

            <div className="space-y-3">
              {sortedPersonaTime.map((persona, index) => (
                <div key={persona.personaName} className="flex items-center space-x-4">
                  <div className="flex-shrink-0 w-8 h-8 bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-full flex items-center justify-center text-sm font-bold">
                    {index + 1}
                  </div>

                  <div className="flex-1">
                    <div className="flex justify-between items-center mb-1">
                      <div>
                        <span className="text-sm font-medium text-gray-900">{persona.personaRole}</span>
                        <span className="text-xs text-gray-500 ml-2">({persona.jobCount} jobs)</span>
                      </div>
                      <div className="text-right">
                        <div className="text-sm font-semibold text-gray-900">
                          {Math.round(persona.totalWeeklyMinutes)} min/week
                        </div>
                        <div className="text-xs text-gray-500">
                          ({(persona.totalWeeklyMinutes / 60).toFixed(1)} hours)
                        </div>
                      </div>
                    </div>

                    <div className="w-full bg-gray-200 rounded-full h-3">
                      <div
                        className="h-3 rounded-full bg-gradient-to-r from-orange-400 to-red-500"
                        style={{ width: `${(persona.totalWeeklyMinutes / Math.max(totalWeeklyTime, 1)) * 100}%` }}
                      />
                    </div>

                    <div className="text-xs text-gray-600 mt-1">
                      {Math.round((persona.totalWeeklyMinutes / Math.max(totalWeeklyTime, 1)) * 100)}% of total time impact
                    </div>
                  </div>
                </div>
              ))}
            </div>

            <div className="mt-6 p-4 bg-orange-50 border border-orange-200 rounded-lg">
              <h5 className="text-sm font-semibold text-orange-800 mb-2">Automation Priority Insights</h5>
              <ul className="text-sm text-orange-700 space-y-1">
                <li>• <span className="font-medium">{sortedPersonaTime[0]?.personaRole}</span> represents the highest automation opportunity with {Math.round(sortedPersonaTime[0]?.totalWeeklyMinutes || 0)} minutes/week</li>
                <li>• Focus agent development on personas with 120+ minutes/week (2+ hours) for maximum impact</li>
                <li>• Target jobs with daily frequency first as they offer consistent time savings</li>
              </ul>
            </div>
          </div>
        ) : (
          <div className="text-center py-12 text-gray-500">
            <BarChart3 className="w-12 h-12 mx-auto mb-4 text-gray-300" />
            <p>No time data available for analysis.</p>
            <p className="text-sm">Add time and frequency information to jobs in Building Mode to see time impact analysis.</p>
          </div>
        )}
      </div>

      {/* Top Opportunities */}
      <div className="bg-white rounded-lg border p-8">
        <h3 className="text-2xl font-bold text-gray-900 mb-6">Priority Agent Opportunities</h3>

        <div className="grid gap-6">
          {visibleAgentOpportunities
            .filter(agent => agent.priority === 'high')
            .slice(0, 3)
            .map((agent, index) => (
              <div key={agent.id} className="flex items-start space-x-4 p-6 bg-gradient-to-r from-blue-50 to-purple-50 rounded-lg border border-blue-200">
                <div className="flex-shrink-0">
                  <div className="w-8 h-8 bg-blue-600 text-white rounded-full flex items-center justify-center font-bold">
                    {index + 1}
                  </div>
                </div>
                <div className="flex-1">
                  <h4 className="text-lg font-semibold text-gray-900 mb-2">{agent.name}</h4>
                  <p className="text-gray-700 mb-3">{agent.description}</p>
                  <div className="flex items-center justify-between">
                    <span className="text-sm text-blue-600 font-medium">Expected Impact: {agent.estimatedImpact}</span>
                  </div>
                </div>
              </div>
            ))}
        </div>

        {visibleAgentOpportunities.filter(a => a.priority === 'high').length === 0 && (
          <div className="text-center py-12 text-gray-500">
            <Target className="w-12 h-12 mx-auto mb-4 text-gray-300" />
            <p>No high-priority agent opportunities identified yet.</p>
            <p className="text-sm">Complete more jobs in Building Mode to generate AI automation recommendations.</p>
          </div>
        )}
      </div>

      {/* Executive Brief */}
      <div className="bg-white rounded-lg border p-8">
        <div className="flex items-center justify-between mb-6">
          <h3 className="text-2xl font-bold text-gray-900">Executive Brief: Agentforce Implementation Strategy</h3>
          <button
            onClick={() => downloadExecutiveBrief()}
            className="flex items-center space-x-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
          >
            <Download className="w-4 h-4" />
            <span>Download Brief</span>
          </button>
        </div>

        <div className="prose max-w-none space-y-8">
          {/* Executive Summary */}
          <div>
            <h4 className="text-lg font-bold text-gray-900 mb-3">Executive Summary</h4>
            <p className="text-gray-700 leading-relaxed">
              We recommend implementing {visibleAgentOpportunities.filter(a => a.priority === 'high').length} high-priority Agentforce agents
              to address {Math.round((visibleJobs.reduce((acc, job) => {
                if (!job.timePerOccurrence || !job.frequency) return acc;
                const multiplier = { 'daily': 5, 'weekly': 1, 'monthly': 0.25, 'as-needed': 1 }[job.frequency] || 1;
                return acc + (job.timePerOccurrence * multiplier);
              }, 0) / 60) * 0.7)} hours per week of manual work across {visiblePersonas.length} key personas.
              This automation initiative will deliver measurable ROI within 90 days through improved efficiency and customer experience.
            </p>
          </div>

          {/* Problem Statement */}
          <div>
            <h4 className="text-lg font-bold text-gray-900 mb-3">Problem Statement</h4>
            <p className="text-gray-700 leading-relaxed">
              Our analysis reveals {visibleJobs.length} critical jobs-to-be-done consuming {Math.round(visibleJobs.reduce((acc, job) => {
                if (!job.timePerOccurrence || !job.frequency) return acc;
                const multiplier = { 'daily': 5, 'weekly': 1, 'monthly': 0.25, 'as-needed': 1 }[job.frequency] || 1;
                return acc + (job.timePerOccurrence * multiplier);
              }, 0) / 60)} hours per week of manual effort. Key pain points include repetitive customer inquiries,
              time-intensive research tasks, and manual data processing. Without automation, these inefficiencies will scale linearly
              with business growth, creating operational bottlenecks and reducing team capacity for strategic initiatives.
            </p>
          </div>

          {/* Options & Trade-offs */}
          <div>
            <h4 className="text-lg font-bold text-gray-900 mb-3">Options & Trade-offs</h4>
            <div className="space-y-3">
              <div className="flex items-start space-x-3">
                <div className="w-2 h-2 bg-blue-500 rounded-full mt-2"></div>
                <div>
                  <strong>Agentforce Implementation:</strong> High automation potential, seamless Salesforce integration.
                  <span className="text-gray-600">Risk: Learning curve for complex workflows.</span>
                </div>
              </div>
              <div className="flex items-start space-x-3">
                <div className="w-2 h-2 bg-gray-400 rounded-full mt-2"></div>
                <div>
                  <strong>Status Quo + Hiring:</strong> Immediate capacity increase, proven approach.
                  <span className="text-gray-600">Risk: Higher costs, scaling limitations, knowledge retention.</span>
                </div>
              </div>
              <div className="flex items-start space-x-3">
                <div className="w-2 h-2 bg-gray-400 rounded-full mt-2"></div>
                <div>
                  <strong>Third-party Tools:</strong> Specialized features, faster initial deployment.
                  <span className="text-gray-600">Risk: Integration complexity, data silos, ongoing costs.</span>
                </div>
              </div>
            </div>
          </div>

          {/* Recommended Plan */}
          <div>
            <h4 className="text-lg font-bold text-gray-900 mb-3">Recommended Execution Plan</h4>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="border-l-4 border-green-500 pl-4">
                <h5 className="font-semibold text-green-800">Phase 1: Foundation (Weeks 1-4)</h5>
                <p className="text-sm text-gray-600">Deploy {Math.min(2, visibleAgentOpportunities.filter(a => a.priority === 'high').length)} high-priority agents</p>
                <p className="text-xs text-gray-500">Owner: IT Team</p>
              </div>
              <div className="border-l-4 border-blue-500 pl-4">
                <h5 className="font-semibold text-blue-800">Phase 2: Scale (Weeks 5-8)</h5>
                <p className="text-sm text-gray-600">Expand to remaining high-priority opportunities</p>
                <p className="text-xs text-gray-500">Owner: Operations Team</p>
              </div>
              <div className="border-l-4 border-purple-500 pl-4">
                <h5 className="font-semibold text-purple-800">Phase 3: Optimize (Weeks 9-12)</h5>
                <p className="text-sm text-gray-600">Monitor performance and refine based on usage data</p>
                <p className="text-xs text-gray-500">Owner: Business Team</p>
              </div>
            </div>
          </div>

          {/* Success Metrics */}
          <div>
            <h4 className="text-lg font-bold text-gray-900 mb-3">Success Metrics & Targets</h4>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <h5 className="font-medium text-gray-900 mb-2">Efficiency Metrics</h5>
                <ul className="space-y-1 text-sm text-gray-700">
                  <li>• 70% reduction in manual processing time (Target: 90 days)</li>
                  <li>• 50% improvement in response times (Target: 60 days)</li>
                  <li>• 90% automation coverage for routine tasks (Target: 120 days)</li>
                </ul>
              </div>
              <div>
                <h5 className="font-medium text-gray-900 mb-2">Business Impact</h5>
                <ul className="space-y-1 text-sm text-gray-700">
                  <li>• 25% increase in team capacity for strategic work</li>
                  <li>• 15% improvement in customer satisfaction scores</li>
                  <li>• ROI positive within 90 days of full deployment</li>
                </ul>
              </div>
            </div>
          </div>

          {/* Risks & Mitigation */}
          <div>
            <h4 className="text-lg font-bold text-gray-900 mb-3">Risks & Mitigation Strategies</h4>
            <div className="space-y-2">
              <div className="flex justify-between items-center p-3 bg-yellow-50 border border-yellow-200 rounded">
                <span className="text-sm"><strong>User Adoption:</strong> Team resistance to new workflows</span>
                <span className="text-xs text-yellow-700">Mitigation: Training program + change champions</span>
              </div>
              <div className="flex justify-between items-center p-3 bg-blue-50 border border-blue-200 rounded">
                <span className="text-sm"><strong>Technical Complexity:</strong> Integration challenges with existing systems</span>
                <span className="text-xs text-blue-700">Mitigation: Phased rollout + dedicated technical support</span>
              </div>
            </div>
          </div>

          {/* Appendix */}
          <div className="border-t pt-6 mt-8">
            <h4 className="text-lg font-bold text-gray-900 mb-3">Appendix: Calculations & Data Sources</h4>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-sm text-gray-600">
              <div>
                <h5 className="font-medium text-gray-900 mb-2">Time Calculations</h5>
                <p>Weekly manual hours: {Math.round(visibleJobs.reduce((acc, job) => {
                  if (!job.timePerOccurrence || !job.frequency) return acc;
                  const multiplier = { 'daily': 5, 'weekly': 1, 'monthly': 0.25, 'as-needed': 1 }[job.frequency] || 1;
                  return acc + (job.timePerOccurrence * multiplier);
                }, 0) / 60)} hours</p>
                <p>Automation potential: 70% (industry benchmark)</p>
                <p>Expected savings: {Math.round((visibleJobs.reduce((acc, job) => {
                  if (!job.timePerOccurrence || !job.frequency) return acc;
                  const multiplier = { 'daily': 5, 'weekly': 1, 'monthly': 0.25, 'as-needed': 1 }[job.frequency] || 1;
                  return acc + (job.timePerOccurrence * multiplier);
                }, 0) / 60) * 0.7)} hours/week</p>
              </div>
              <div>
                <h5 className="font-medium text-gray-900 mb-2">Data Sources</h5>
                <p>Jobs analysis: {visibleJobs.length} documented jobs</p>
                <p>Persona research: {visiblePersonas.length} key roles</p>
                <p>Agent opportunities: {visibleAgentOpportunities.length} identified</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );

  return (
    <div>
      {/* Export Actions */}
      <div className="mb-6 flex justify-end space-x-3">
        <button
          onClick={() => downloadExecutiveBrief()}
          className="flex items-center space-x-2 px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50"
        >
          <Download className="w-4 h-4" />
          <span>Download Executive Brief</span>
        </button>
        <button className="flex items-center space-x-2 px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50">
          <Presentation className="w-4 h-4" />
          <span>Generate Slides</span>
        </button>
      </div>

      {/* Executive Dashboard */}
      {renderExecutiveDashboard()}
    </div>
  );
}